version: 1

jobs:
    build:
        docker:
            - image: "rikorose/gcc-cmake:gcc-7"
        steps:
            - checkout
            - run:
                name: Installing SUDO
                command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
            - run:
                name: Creating CMAKE Files
                command: 'cmake .'
            - run:
                name: Build
                command: 'make'
